select * from hc limit 10;

# Question 1 : What is the total revenue (Billing_Amount) and patient count generated by Male vs. Female patients?
select Gender,
round(sum(Billing_Amount),2), count(*) from hc
where Gender in ("Male", "Female")
group by Gender;


# Question 2 : Which patients had an 'Emergency' admission type but still incurred a Billing_Amount higher than the overall average billing amount?
select name, admission_type, Billing_Amount from hc
where admission_type = "Emergency" 
and Billing_Amount > (select avg(Billing_Amount) from hc);


# Question 3 : What are the top 5 medical conditions with the highest average length of stay (Days_Stayed)?
select round(avg(days_stayed), 2) as avg_days_stayed , medical_condition from hc
group by Medical_Condition
order by avg_days_stayed desc limit 5;


# Question 4 : Compare the average Billing_Amount and average Days_Stayed between Emergency, Urgent, and Elective admission types
with avg_bill as (
  select admission_type, round(avg(Billing_Amount), 2) as avg_bill_amount from hc
  group by Admission_Type

),
avg_days as (
  select admission_type, round(avg(Days_Stayed),2) as avg_days_stayed from hc
  group by Admission_Type
)

select b.admission_type, b.avg_bill_amount, d.admission_type ,d.avg_days_stayed
from avg_bill b
left join avg_days d on b.admission_type = d.admission_type;

  
  
# Question 5 : Do patients with 'Abnormal' test results spend more money? 
# Compare average Billing_Amount and total revenue across Normal, Inconclusive, and Abnormal test results

select Test_Results, 
round(avg(Billing_Amount), 2) as Avg_Billing_Amount,
round(sum(Billing_Amount), 2) as Total_Revenue from hc
where Test_Results in ("Normal", "Inconclusive", "Abnormal")
group by Test_Results;

# Answer : No "Abnormal" Test result patient does not spend more compared to  Normal, Inconclusive



# Question 6 : Which 3 insurance providers have the highest percentage of patients falling into the 'High Fees' Billing_Category?
SELECT 
    Insurance_Provider,
    ROUND(AVG(Billing_Category = 'High Fees') * 100, 2) AS high_fee_percentage
FROM hc
GROUP BY Insurance_Provider
ORDER BY high_fee_percentage DESC
LIMIT 3;



# Question 7 : Segment patients into 'Short Stay' (1-5 days), 'Medium Stay' (6-15 days), and 'Long Stay' (>15 days), and display the patient count and average Billing_Amount for each segment
select count(*) as Patient_Count, round(avg(Billing_Amount),2) as avg_billing_amount,
case 
  when Days_stayed between 1 and 5 then "Short Stay"
  when Days_stayed between 6 and 15 then "Medium Stay"
  when Days_stayed > 15 then "Long Stay"
end as Stay_Category
from hc
group by Stay_Category;


# Question 8 : What are the top 3 doctors with the highest total revenue generated within each Medical_Condition?

WITH RankedDoctors AS (
    SELECT 
        Medical_Condition,
        Doctor,
        ROUND(SUM(Billing_Amount), 2) AS total_revenue,
        DENSE_RANK() OVER (
            PARTITION BY Medical_Condition 
            ORDER BY SUM(Billing_Amount) DESC
        ) AS dr_rank
    FROM hc
    GROUP BY Medical_Condition, Doctor
)
SELECT 
    Medical_Condition,
    Doctor,
    total_revenue,
    dr_rank
FROM RankedDoctors
WHERE dr_rank <= 3
ORDER BY Medical_Condition, dr_rank;














  
  
  
  
  
  
  
  
  
  
  
